typography_spectrum: 0.5869121295399964
color:
  brandStrength: 0.025090034352615476
  lightness: 0.452123363269493
  saturation: 0.6929979585111141
  rhythmicContrast: 0.7911253841593862
  brandColors:
    - '#0095CF'
    - '#000023'
    - '#27C1ED'
    - '#003376'
    - '#A8EFFB'
layout_spectrum: 0.8711371631361544
name: Cenor Group
navigation:
  - name: Asset Management
    url: 'http://cenorgroup.com/asset_management.php'
    type: external
title: Investment Management
description: Global service
